import React from 'react'

import dash from './../../assets/images/numbers/null.png'
import ten from './../../assets/images/numbers/10.png'
import nine from './../../assets/images/numbers/09.png'
import eight from './../../assets/images/numbers/08.png'
import seven from './../../assets/images/numbers/07.png'
import six from './../../assets/images/numbers/06.png'
import five from './../../assets/images/numbers/05.png'
import four from './../../assets/images/numbers/04.png'
import three from './../../assets/images/numbers/03.png'
import two from './../../assets/images/numbers/02.png'
import one from './../../assets/images/numbers/01.png'
import zero from './../../assets/images/numbers/00.png'
import eleven from './../../assets/images/numbers/11.png'
import twelve from './../../assets/images/numbers/12.png'
import thirteen from './../../assets/images/numbers/13.png'
import fourteen from './../../assets/images/numbers/14.png'
import fifteen from './../../assets/images/numbers/15.png'
import sixteen from './../../assets/images/numbers/16.png'
import seventeen from './../../assets/images/numbers/17.png'
import eighteen from './../../assets/images/numbers/18.png'
import nineteen from './../../assets/images/numbers/19.png'
import twenty from './../../assets/images/numbers/20.png'
import twentyone from './../../assets/images/numbers/21.png'
import twentytwo from './../../assets/images/numbers/22.png'
import twentythree from './../../assets/images/numbers/23.png'
import twentyfour from './../../assets/images/numbers/24.png'
import twentyfive from './../../assets/images/numbers/25.png'
import twentysix from './../../assets/images/numbers/26.png'
import twentyseven from './../../assets/images/numbers/27.png'
import twentyeight from './../../assets/images/numbers/28.png'
import twentynine from './../../assets/images/numbers/29.png'
import thirty from './../../assets/images/numbers/30.png'
import thirtyone from './../../assets/images/numbers/31.png'
import thirtytwo from './../../assets/images/numbers/32.png'
import thirtythree from './../../assets/images/numbers/33.png'
import thirtyfour from './../../assets/images/numbers/34.png'
import thirtyfive from './../../assets/images/numbers/35.png'
import thirtysix from './../../assets/images/numbers/36.png'
import thirtyseven from './../../assets/images/numbers/37.png'
import thirtyeight from './../../assets/images/numbers/38.png'
import thirtynine from './../../assets/images/numbers/39.png'
import forty from './../../assets/images/numbers/40.png'
import fortyone from './../../assets/images/numbers/41.png'
import fortytwo from './../../assets/images/numbers/42.png'
import fortythree from './../../assets/images/numbers/43.png'
import fortyfour from './../../assets/images/numbers/44.png'
import fortyfive from './../../assets/images/numbers/45.png'
import fortysix from './../../assets/images/numbers/46.png'
import fortyseven from './../../assets/images/numbers/47.png'
import fortyeight from './../../assets/images/numbers/48.png'
import fortynine from './../../assets/images/numbers/49.png'


const Number = [dash, one, two, three, four, five, six, seven, eight, nine, ten, eleven, 
    twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty,
    twentyone, twentytwo, twentythree, twentyfour, twentyfive, twentysix, twentyseven, twentyeight, twentynine, thirty,
    thirtyone, thirtytwo, thirtythree, thirtyfour, thirtyfive, thirtysix, thirtyseven, thirtyeight, thirtynine, forty, 
    fortyone, fortytwo, fortythree, fortyfour, fortyfive, fortysix, fortyseven, fortyeight, fortynine
];
export default Number